### ISSUE TITLE
Login url 0m appended

### ISSUE THREAD

**Issue by J0n4t4n** [MinisculeGirraffe/tdl#10]
Hi,
I've just tried tdl for the first time and using the login command I got an invalid URL.
After looking at it I found that something seems to always append "0m" to the end of the URL.

Examples:
Please Login to Tidal: https://link.tidal.com/DTRBT0m
Please Login to Tidal: https://link.tidal.com/UDLES0m

Removing the 0m makes the url valid.

**Comment by MinisculeGirraffe** [comment]
That's due to the ANSI hyperlink being added to the URl. I'm just going to disable that for now
