### ISSUE TITLE
Stalled threads during downloads.

### ISSUE THREAD

**Issue by cleonyc** [MinisculeGirraffe/tdl#28]
When downloading more than one album at a time, after about 3-4 albums are done downloading, threads die from rate limits from the tidal servers, resulting in many albums only having certain songs be downloaded. I will be implementing an option to sleep between album downloads in a future PR. 

Confirmed by @popeye2468 further in the comments on #26.

**Comment by MinisculeGirraffe** [comment]
I'm going to close this in favor of #29 you opened. I don't think a delay is the right way to go about it.

if you do want to edit one in, it should just be a call to [tokio::sleep](https://docs.rs/tokio/latest/tokio/time/fn.sleep.html) [here](https://github.com/MinisculeGirraffe/tdl/blob/main/src/download.rs#L114) 

I don't know that it would be the best solution though for the reasons I specified in the other issue.
